version: '3'
services:
  react-ui:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
