version: '3'
services:
  react-ui:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
  mongodb:
      image: mongo
      container_name: mongo
      restart: unless-stopped
      command: mongod --auth
      environment:
          MONGO_INITDB_ROOT_USERNAME: "admin"
          MONGO_INITDB_ROOT_PASSWORD: "password"
          MONGO_INITDB_DATABASE: webapp
          MONGODB_DATA_DIR: /data/db
      volumes:
          - mongodbdata:/data/db
      networks:
          - backend
  api:
    build: 
        context: ./backend
        dockerfile: Dockerfile
    #command: gunicorn --bind 0.0.0.0:5000 app:app
    ports:
        - "80:80"
    container_name: api
    restart: always
    environment:
        MONGODB_HOST: mongodb
        MONGODB_USERNAME: "apiuser"
        MONGODB_PASSWORD: "apipassword"
    volumes:
        - appdata:/var/www/
    #depends_on: 
    #    - mongodb
    networks:
        - frontend
        - backend

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
volumes:
    mongodbdata:
        driver: local
    appdata:
        driver: local


